// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Sat Mar 18 15:05:31 2017

PC PC_inst
(
	.EN(EN_sig) ,	// input  EN_sig
	.i_dir(i_dir_sig) ,	// input [31:0] i_dir_sig
	.clk(clk_sig) ,	// input  clk_sig
	.o_dir(o_dir_sig) 	// output [31:0] o_dir_sig
);

